### ISSUE TITLE
questions prior to install

### ISSUE THREAD

**Issue by atomGit** [mattyrob/subscribe2-for-cp#1]
* what was readygraph? i assume this was some scheme to monetize the plugin which has since been removed?
* is there any monetization scheme in use currently?
* is the developer who implemented readygraph still involved in this project?

on another note...

last time i tested the plugin i don't recall that public subscribers were sent a mail to confirm their subscription - in the FAQs it says they are - can you confirm?

i don't wish to make people create a user/password for subscribing - in that vein, it would be great if public subscribers could choose categories - i know you don't wish to dynamically generate a page for the purpose, but i'm wondering if there's another way, such as craigslist does it by auto-generating a password string in the URL - could this be passes as a URL parameter to a static page?

[typo](https://subscribe2.wordpress.com/support/faqs/#16)...

"When they enter there address"
should be...
"When they enter their address"

thanks!

**Comment by mattyrob** [comment]
@atomGit 

- ReadyGraph was an attempt to monetise Subscribe2, when I sold the code in 2014 to new developers they introduced it.
- Mail OptIn (https://mailoptin.io) is currently included but it's not as intrusive IMO.
- No, ReadyGraph sold the plugin on again to MailOptIn

Public Subscribers have always received an email with a link to click to confirm their sign up to email notifications - in many countries that 2 step  process is required by law.

The plugin is currently code in such as way that a huge re-write would be needed to enable category level subscriptions for Public Subscribers - the database table for a start would need new columns and a method would need writing to add the correct data to the email address while also preserving existing subscribers with full subscription. The security steps to ensure only the email address owner can make those changes would also mean it would have to be a two step process again.

Officially, Subscribe2 is not mine, I just have this branch here and share enhancements and fixes from Subscribe2 HTML (which is still mine) with the free version. I would be unlikely to add category subscriptions for Public Subscribers in the future but I'm not sure where the current code owner wants to take it.
