### ISSUE TITLE
PHP Fatal error. Both manual and upload installation.

### ISSUE THREAD

**Issue by ghost** [mattyrob/subscribe2-for-cp#4]
Greetings!,

First,  thanks for developing this plugin!!  Copying the plugin directory (or git cloning) into the plugin directory will crash the front-end of the website (not wp-admin area). No activation needed for this to happen. Screen goes white. See more below.

Running on a freshly installed classicpress test site with the default theme and no other plugins.  No activation needed for the PHP Fatal error. Removing the plugin (deleting) fixes the issue.  This effects the entire front-end but the wp-admin area and Subscribe2 settings pages in the admin interface works. 

**Note:** I am digging into this bug but wanted to post this to help me track the issue.

Running Debian 10 with the most recent versions of PHP, Apache and MariaDB.

* mariadb  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

* PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )

* Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

* Apache 2.4.38

**Error as follows:**

[Wed Jul 21 14:04:25.939715 2021] [php7:warn] [pid 25013] [client 174.206.0.101:24989] PHP Warning:  require_once(/home/james/test/htdocs/wp-content/plugins/subscribe2-for-cp/classes/class-s2-captcha.php): failed to open stream: No such file or directory in /home/james/test/htdocs/wp-content/plugins/subscribe2-for-cp/classes/class-s2-frontend.php on line 53, referer: https://test.jamesburnett.io/wp-admin/widgets.php
[Wed Jul 21 14:04:25.939949 2021] [php7:error] [pid 25013] [client 174.206.0.101:24989] PHP Fatal error:  require_once(): Failed opening required '/home/james/test/htdocs/wp-content/plugins/subscribe2-for-cp/classes/class-s2-captcha.php' (include_path='.:/usr/share/php') in /home/james/test/htdocs/wp-content/plugins/subscribe2-for-cp/classes/class-s2-frontend.php on line 53, referer: https://test.jamesburnett.io/wp-admin/widgets.php

**Comment by ghost** [comment]
Looks like the "class-s2-captcha.php" file is missing.

**Comment by mattyrob** [comment]
@jamesburnettio - Thanks for a very helpful bug report

I have a fix pushed for this now and will release a new version shortly - thanks again

**Comment by ghost** [comment]
> @jamesburnettio - Thanks for a very helpful bug report
> 
> I have a fix pushed for this now and will release a new version shortly - thanks again

**Comment by mattyrob** [comment]
New release is available at version 11.5 that should fix this ;)
