### ISSUE TITLE
Reply-To E-Mail in CP Subscribe2

### ISSUE THREAD

**Issue by LaOrhyUAcMji** [mattyrob/subscribe2-for-cp#5]
I'm using a multisite setup. I've already installed the ClassicPress SMTP plugin and configured it for the sites in the multisite network. However, when sending a mail from one of the sites, the reply-to e-mail address is that of the site admin, instead of the SMTP email specified in the CP SMTP plugin.
Can the reply-to email address be configured to be identical to the SMTP email when using Subscribe2?
I've tested the email sending with FluentForms and this issue isn't replicated there, which implies its a settings issue in Subscribe2, and not in the SMTP plugin.
Thanks for all the amazing work, hope this issue can be easily resolved.

**Comment by mattyrob** [comment]
@noellarkin 

Hi, and thanks for the question.

**Subscribe2 for ClassicPress** can be activated at site level on a Multisite install as I'm sure you already know.

The 'From' email address used by **Subscribe2 for ClassicPress** is configured in the _Subscribe2 > Settings_ pages in the first tab. There is a drop down selector where it says "Send Email From".

In here you have 'Post Author' as the first option - this will send the emails from the email address of the user account that clicks to publish the post. The next option is from the 'blog' and that uses the email address defined at the core settings page under _Settings > General_. And then you will have individual user accounts listed that have 'administrator' user level.

If you need to, you may want to create an administrator level account on the blog with the required email address and then update the options in **Subscribe2 for ClassicPress** to use that account for sending the emails.

I hope that helps answer the question.

**Comment by LaOrhyUAcMji** [comment]
Thank you!
Yes that does make sense - - I made a separate admin level account and tried with that, and that worked just fine!
An additional question, if you don't mind. I'm using WP-Pods to manage different post types. Subscribe2 seems to have Posts and Pages in its settings, but is there any way I can extend that to custom post types?

**Comment by mattyrob** [comment]
@noellarkin 

Custom Post Types are supported via an API so you will need to write a little bit of code. See the `s2_post_types` filter as described in the [API documentation](https://subscribe2.wordpress.com/support/api/).
