### ISSUE TITLE
Zip package does not contain main folder.

### ISSUE THREAD

**Issue by ghost** [mattyrob/subscribe2-for-cp#6]
Every other classicpress plugin stores the source files inside a folder which is named after the plugin. When unzipping subscribe2-for-cp a "root" folder for the plugin is not create and all the source files go directly into the root folder. This goes agains the "how everyone else" does it.

classic-seo, azrcrv-smtp and others created actual folders to place the content of their plugin into while subscribe2 just dumps everything into the root of the plugins folder, which creates a bit of a mess.

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/86435903/160119329-ef84569b-ce4b-43f5-8808-caaaeb3739b7.png">

**Comment by mattyrob** [comment]
Thanks @jamesburnettio for the helpful bug report.

I'll push an update to my build script shortly that will fix this ready for the next release.

**Comment by mattyrob** [comment]
Fixed in:
https://github.com/mattyrob/subscribe2-for-cp/commit/222d052fce8c1500859489f9df9c61e33a6582c1
